# TikZ drawings of the estimated Danube graphs.

suppressPackageStartupMessages({
  library(MASS); library(igraph); library(graphicalExtremes)
})
source("experiment_helpers.R")

data(danube, package = "graphicalExtremes")
X <- danube$data_clustered
d <- ncol(X)
p_thresh <- 0.90
Gamma_full <- emp_vario(data = X, p = p_thresh)

K_emtp2 <- fit_emtp2(Gamma_full)
emtp2_adj <- (abs(K_emtp2) > 1e-3) & (row(K_emtp2) != col(K_emtp2))

eta_bic <- 4
mle <- hr_mle_dense(Gamma_full, tol = 1e-8, maxiter = 3000)
sp_res <- spectral_hr_from_mle(mle, eta_bic, tol = 1e-8, maxiter = 3000)
K_spectral <- sp_res$Theta_refit
sp_adj <- (abs(K_spectral) > 1e-3) & (row(K_spectral) != col(K_spectral))

cat(sprintf("EMTP2 edges: %d\n", sum(emtp2_adj[upper.tri(emtp2_adj)])))
cat(sprintf("Spectral-HR (BIC-selected eta=%g) edges: %d\n",
            eta_bic, sum(sp_adj[upper.tri(sp_adj)])))

node_x <- c(257.31, 200.31, 143.30, 143.30, 200.31, 200.31, 200.31,
            200.31, 200.31, 200.31, 143.30, 143.30,
            314.32, 257.31, 314.32, 314.32, 314.32, 314.32, 314.32,
            257.31, 257.31, 257.31,
            143.30, 143.30,
            86.30, 86.30, 86.30,
            371.32, 371.32, 371.32, 371.32)
node_y <- c(365.32, 348.56, 331.79, 298.26, 298.26, 264.73, 231.19,
            197.66, 164.13, 130.60, 113.83, 80.30,
            348.56, 331.79, 315.02, 281.49, 247.96, 214.43, 180.89,
            197.66, 164.13, 130.60,
            264.73, 231.19,
            298.26, 264.73, 231.19,
            264.73, 231.19, 331.79, 298.26)
stopifnot(length(node_x) == d, length(node_y) == d)
label_y <- node_y - 3.20

write_graph_tikz <- function(adj, file_out) {
  con <- file(file_out, open = "w")
  on.exit(close(con), add = TRUE)
  cat(file = con,
      "% Auto-generated by generate_danube_tikz.R\n",
      "\\begin{tikzpicture}[x=1pt,y=1pt]\n",
      "\\definecolor{fillColor}{RGB}{255,255,255}\n",
      "\\path[use as bounding box,fill=fillColor,fill opacity=0.00] (0,0) rectangle (433.62,433.62);\n",
      "\\begin{scope}\n",
      "\\path[clip] ( 49.20, 61.20) rectangle (408.42,384.42);\n",
      "\\definecolor{drawColor}{RGB}{169,169,169}\n\n",
      sep = "")
  for (i in seq_len(d - 1)) {
    for (j in seq.int(i + 1, d)) {
      if (!isTRUE(adj[i, j])) next
      cat(file = con, sprintf(
        "\\path[draw=drawColor,line width= 0.8pt,line join=round,line cap=round] (%6.2f,%6.2f) -- (%6.2f,%6.2f);\n\n",
        node_x[i], node_y[i], node_x[j], node_y[j]))
    }
  }
  cat(file = con,
      "\\definecolor{drawColor}{RGB}{0,0,0}\n",
      "\\definecolor{fillColor}{RGB}{173,216,230}\n\n",
      sep = "")
  for (i in seq_len(d)) {
    cat(file = con, sprintf(
      "\\path[draw=drawColor,line width= 0.4pt,line join=round,line cap=round,fill=fillColor] (%6.2f,%6.2f) circle (  7.13);\n\n",
      node_x[i], node_y[i]))
  }
  cat(file = con, "\\end{scope}\n\\begin{scope}\n",
      "\\path[clip] (  0.00,  0.00) rectangle (433.62,433.62);\n",
      "\\definecolor{drawColor}{RGB}{0,0,139}\n\n",
      sep = "")
  for (i in seq_len(d)) {
    cat(file = con, sprintf(
      "\\node[text=drawColor,anchor=base,inner sep=0pt, outer sep=0pt, scale=  1.00] at (%6.2f,%6.2f) {%d};\n\n",
      node_x[i], label_y[i], i))
  }
  cat(file = con, "\\end{scope}\n\\end{tikzpicture}\n", sep = "")
}

out_emtp2 <- normalizePath("../emtp2_graph.tex", winslash = "/", mustWork = FALSE)
out_sp    <- normalizePath("../spectral_hr_bic_graph.tex", winslash = "/", mustWork = FALSE)
write_graph_tikz(emtp2_adj, out_emtp2)
write_graph_tikz(sp_adj,    out_sp)
cat(sprintf("Wrote %s\n", out_emtp2))
cat(sprintf("Wrote %s\n", out_sp))
