# Emit the LaTeX table body for the LCGGM simulation results.

res <- function(f) file.path("..", "results", f)

SETTINGS <- list(
  list(tag = "d100_er",  label = "ER, $d=100$",  truth = 176),
  list(tag = "d100_sbm", label = "SBM, $d=100$", truth = 171),
  list(tag = "d200_er",  label = "ER, $d=200$",  truth = 391),
  list(tag = "d200_sbm", label = "SBM, $d=200$", truth = 623)
)
METHODS <- c("CGL (Egilmez 2017)"          = "CGL",
             "NGL-SCAD (Ying 2020 NeurIPS)" = "NGL-SCAD",
             "Spectral-LCGGM (ours)"        = "Spectral-LCGGM")

fmt <- function(x, digits) {
  s <- formatC(x, format = "f", digits = digits, big.mark = ",")
  gsub(",", "{,}", s, fixed = TRUE)
}
cell <- function(v, se, digits, best, phantom = FALSE) {
  num  <- fmt(v, digits)
  body <- if (best) sprintf("\\mathbf{%s}", num) else num
  ph   <- if (phantom && !grepl("{,}", num, fixed = TRUE)) "\\phantom{1{,}}" else ""
  sprintf("$%s%s\\,(%s)$", ph, body, fmt(se, digits))
}

out <- c("%% ---- TABLE 1 (LCGGM simulation) ---- generated by code/make_lcggm_table.R")
for (si in seq_along(SETTINGS)) {
  st <- SETTINGS[[si]]
  d <- read.csv(res(sprintf("sim_lcggm_ersbm_%s_summary.csv", st$tag)),
                stringsAsFactors = FALSE)
  d <- d[match(names(METHODS), d$method), ]
  if (anyNA(d$method))
    stop("missing methods in ", st$tag, ": ",
         paste(setdiff(names(METHODS), d$method), collapse = ", "))

  best_edges <- which.min(abs(d$edges_mean - st$truth))
  best <- list(edges = best_edges,
               precision = which.max(d$precision_mean),
               recall    = which.max(d$recall_mean),
               f1        = which.max(d$f1_mean),
               ll        = which.max(d$test_loglik_mean))

  out <- c(out, sprintf(
    "\\multirow{3}{*}{\\shortstack[l]{%s\\\\$|E^\\star|=%d$}}", st$label, st$truth))
  for (i in seq_len(nrow(d))) {
    r <- d[i, ]
    out <- c(out, sprintf(
      "  & %-16s & %s & %s & %s & %s & %s & %s \\\\",
      METHODS[[r$method]],
      cell(r$edges_mean, r$edges_se, 1, i == best$edges, phantom = TRUE),
      cell(r$precision_mean, r$precision_se, 3, i == best$precision),
      cell(r$recall_mean, r$recall_se, 3, i == best$recall),
      cell(r$f1_mean, r$f1_se, 3, i == best$f1),
      cell(r$test_loglik_mean, r$test_loglik_se, 0, i == best$ll),
      sprintf("$%s\\,(%s)$", fmt(r$time_sec_mean, 0), fmt(r$time_sec_se, 0))))
  }
  if (si < length(SETTINGS)) out <- c(out, "\\midrule")
}

writeLines(out, res("lcggm_table.tex"))
cat("written to results/lcggm_table.tex\n")
cat(paste(out, collapse = "\n"), "\n")

cat("\n--- claims to verify in the text ---\n")
for (st in SETTINGS) {
  d <- read.csv(res(sprintf("sim_lcggm_ersbm_%s_summary.csv", st$tag)),
                stringsAsFactors = FALSE)
  sp <- d[d$method == "Spectral-LCGGM (ours)", ]
  cg <- d[d$method == "CGL (Egilmez 2017)", ]
  ng <- d[d$method == "NGL-SCAD (Ying 2020 NeurIPS)", ]
  cat(sprintf("%-9s edges %+5.1f%% of truth | F1 %.3f | Spectral/CGL time %.1fx | Spectral/NGL %.1fx\n",
              st$tag, 100 * (sp$edges_mean - st$truth) / st$truth, sp$f1_mean,
              sp$time_sec_mean / cg$time_sec_mean,
              sp$time_sec_mean / ng$time_sec_mean))
}
