# Emit the LaTeX table bodies for the Husler-Reiss results.

res <- function(f) file.path("..", "results", f)

fmt <- function(x, digits = 2) {
  if (is.na(x)) return("---")
  s <- formatC(x, format = "f", digits = digits, big.mark = ",")
  gsub(",", "{,}", s, fixed = TRUE)
}
bf <- function(s) paste0("\\mathbf{", s, "}")
m  <- function(s) paste0("$", s, "$")

out <- character(0)
add <- function(...) out <<- c(out, paste0(...))

d <- read.csv(res("realdata_hr_danube_nosplit.csv"), stringsAsFactors = FALSE)
best_bic <- min(d$BIC); best_aic <- min(d$AIC); best_edg <- min(d$edges)
cell <- function(v, is_best, digits = 2) {
  s <- fmt(v, digits); m(if (is_best) bf(s) else s)
}
row_lab <- c(EMTP2 = "\\EMTPtwo{}", "eglearn-NS" = "eglearn-NS",
             "eglearn-glasso" = "eglearn-glasso", "Spectral-HR" = "Spectral-HR")

add("%% ---- TABLE 2 (Danube summary) ---- generated by code/make_hr_tables.R")
for (i in seq_len(nrow(d))) {
  r <- d[i, ]
  par <- if (is.na(r$param)) "--" else m(fmt(r$param, if (r$method == "Spectral-HR") 0 else 3))
  add(sprintf("%s & %s & %s & %s & %s & %s & %s \\\\",
              row_lab[[r$method]], r$criterion, par,
              cell(r$edges, r$edges == best_edg, 0),
              cell(r$BIC, isTRUE(all.equal(r$BIC, best_bic))),
              cell(r$AIC, isTRUE(all.equal(r$AIC, best_aic))),
              m(fmt(r$time_sec, 1))))
}

add("", "%% ---- TABLE 3 (Texas Cluster) ---- generated by code/make_hr_tables.R")
f <- read.csv(res("realdata_hr_flights_tc.csv"), stringsAsFactors = FALSE)
lab3 <- c("EMTP2" = "\\EMTPtwo{}",
          "eglearn-NS (Engelke et al)" = "eglearn-NS",
          "eglearn-glasso (Engelke et al)" = "eglearn-glasso",
          "Spectral-HR (ours)" = "Spectral-HR")
b_edg <- min(f$n_edges); b_bic <- min(f$train_bic)
b_aic <- min(f$train_aic); b_ll  <- max(f$test_loglik)
span <- function(n, s) if (n > 1) sprintf("\\multirow{%d}{*}{%s}", n, s) else s

meths <- unique(f$method)
for (mi in seq_along(meths)) {
  idx <- which(f$method == meths[mi])
  if (length(idx) == 2L &&
      isTRUE(all.equal(f$param[idx[1]], f$param[idx[2]])) &&
      f$n_edges[idx[1]] == f$n_edges[idx[2]]) {
    f$criterion[idx[1]] <- paste(f$criterion[idx], collapse = " \\& ")
    idx <- idx[1]
  }
  nm <- length(idx)
  for (r in seq_along(idx)) {
    row <- f[idx[r], ]
    par <- if (is.na(row$param)) "--" else
      m(fmt(row$param, if (grepl("Spectral", row$method)) 0 else 3))
    add(sprintf("%s & %s & %s & %s & %s & %s & %s & %s \\\\",
                if (r == 1) span(nm, lab3[[row$method]]) else "",
                row$criterion, par,
                cell(row$n_edges,   row$n_edges == b_edg, 0),
                cell(row$train_bic, isTRUE(all.equal(row$train_bic, b_bic)), 1),
                cell(row$train_aic, isTRUE(all.equal(row$train_aic, b_aic)), 1),
                cell(row$test_loglik, isTRUE(all.equal(row$test_loglik, b_ll)), 1),
                if (r == 1) span(nm, m(fmt(row$time_sec, 1))) else ""))
  }
  if (mi < length(meths)) add("\\midrule")
}
cat(sprintf("Texas selections: %s\n",
            paste(f$method, f$criterion, f$param, sep = "/", collapse = ", ")))

sweep_block <- function(file, parname, digits) {
  p <- read.csv(res(file), stringsAsFactors = FALSE)
  names(p)[1] <- "param"
  ok <- !is.na(p$BIC)
  bb <- if (any(ok)) which(p$BIC == min(p$BIC[ok]))[1] else NA
  ba <- if (any(ok)) which(p$AIC == min(p$AIC[ok]))[1] else NA
  last_ok <- if (any(ok)) max(which(ok)) else 0L
  rows <- character(0)
  if (last_ok < nrow(p)) {
    p <- p[seq_len(last_ok + 1L), , drop = FALSE]
  }
  for (i in seq_len(nrow(p))) {
    r <- p[i, ]
    if (is.na(r$BIC)) {
      rows <- c(rows, sprintf("%s & --- & --- & --- \\\\",
                              m(paste0("\\ge ", fmt(r$param, digits)))))
      next
    }
    rows <- c(rows, sprintf("%s & %s & %s & %s \\\\",
                            m(fmt(r$param, digits)),
                            m(fmt(r$edges, 0)),
                            m(if (identical(i, bb)) bf(fmt(r$BIC)) else fmt(r$BIC)),
                            m(if (identical(i, ba)) bf(fmt(r$AIC)) else fmt(r$AIC))))
  }
  rows
}
add("", "%% ---- TABLE 4(a) Spectral-HR eta sweep ----")
out <- c(out, sweep_block("realdata_hr_danube_nosplit_spectral_path.csv", "eta", 2))
add("", "%% ---- TABLE 4(b) eglearn-NS rho sweep ----")
out <- c(out, sweep_block("realdata_hr_danube_nosplit_eglearn_ns_path.csv", "rho", 3))
add("", "%% ---- TABLE 4(c) eglearn-glasso rho sweep ----")
out <- c(out, sweep_block("realdata_hr_danube_nosplit_eglearn_glasso_path.csv", "rho", 3))

writeLines(out, res("hr_tables.tex"))
cat("written to results/hr_tables.tex\n")
cat(paste(out, collapse = "\n"), "\n")
